spring.application.name=roadsafety

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/roadsafety_db
spring.datasource.username=root
spring.datasource.password=Bharat@1425

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=8080
